Update beyondcorp.sh
GoogleCloudPlatform/beyondcorp-applink pull request #25
Opened 2021-11-17 07:38 UTC by shixiong-jiang

2021-11-17 19:12 UTC, zixunjian commented on bash-scripts/cli/beyondcorp.sh
> +# TODO: add app list cmd
Remove all TODOs

2021-11-17 19:22 UTC, brettmeehan-google requested changes

2021-11-17 19:22 UTC, brettmeehan-google commented on bash-scripts/cli/beyondcorp.sh
> +# TODO: add app list cmd
Remove TODO

2021-11-17 19:22 UTC, brettmeehan-google commented on bash-scripts/cli/beyondcorp.sh
> +# TODO: explore using nftables in place of iptables
Remove TODO

2021-11-17 19:22 UTC, brettmeehan-google commented on bash-scripts/cli/beyondcorp.sh
> +  # TODO: rollback behavior
Remove TODO

2021-11-18 17:22 UTC, brettmeehan-google approved these changes

2021-11-18 17:23 UTC, merged